### PR TITLE
agent: honour CPU constraints when agent is the init process

### LINKED ISSUE #262: cgroup is not working with initrd
Using the following configuration:
kata-runtime  : 1.0.0
commit   : dd2bf15ebc7691322117d79c7a004f01267aca13
OCI specs: 1.0.1
kata-agent version 1.0.0-ac573e21f6b13b0ce2f9659b31f53a6ffd7b1622
kata-shim version 1.0.0-087a5371680f069d45baed8544a09b4e6353c06e
kata-proxy version 1.0.0-a69326b63802952b14203ea9c1533d4edb8c1d64
And enabling initrd with
AGENT_INIT=yes TEST_INITRD=yes OSBUILDER_DISTRO=alpine

The docker integration tests for cpu are failing
```
Update CPU constraints Update number of CPUs to check period and quota
  quota/period should be equal to 0.5
  /home/gaby/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46
Running command '/usr/bin/docker [docker run --runtime kata-runtime --rm --name e85ARtHu5vel2xRF4MBDGUXeUr1VqK -dt debian bash]'
[docker run --runtime kata-runtime --rm --name e85ARtHu5vel2xRF4MBDGUXeUr1VqK -dt debian bash]
Timeout: 5 seconds
Exit Code: 0
Stdout: eb549d088917dff7c7897219661a0fd536998960d89df663f00c9d5bd61fe908

Stderr:
Running command '/usr/bin/docker [docker update --cpus 0.500000 e85ARtHu5vel2xRF4MBDGUXeUr1VqK]'
[docker update --cpus 0.500000 e85ARtHu5vel2xRF4MBDGUXeUr1VqK]
Timeout: 5 seconds
Exit Code: 0
Stdout: e85ARtHu5vel2xRF4MBDGUXeUr1VqK

Stderr:
Running command '/usr/bin/docker [docker exec e85ARtHu5vel2xRF4MBDGUXeUr1VqK bash -c perl -e "printf ('%.1f', $(cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us)/$(cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_period_us))"]'
command failed error 'exit status 255'
[docker exec e85ARtHu5vel2xRF4MBDGUXeUr1VqK bash -c perl -e "printf ('%.1f', $(cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us)/$(cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_period_us))"]
Timeout: 5 seconds
Exit Code: 255
Stdout:
Stderr: cat: /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us: No such file or directory
cat: /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_period_us: No such file or directory
Search pattern not terminated at -e line 1.

Running command '/usr/bin/docker [docker rm -f e85ARtHu5vel2xRF4MBDGUXeUr1VqK]'
[docker rm -f e85ARtHu5vel2xRF4MBDGUXeUr1VqK]
Timeout: 5 seconds
Exit Code: 0
Stdout: e85ARtHu5vel2xRF4MBDGUXeUr1VqK

Stderr:
Running command '/usr/bin/docker [docker ps -a -f name=e85ARtHu5vel2xRF4MBDGUXeUr1VqK --format {{.Status}}]'
[docker ps -a -f name=e85ARtHu5vel2xRF4MBDGUXeUr1VqK --format {{.Status}}]
Timeout: 5 seconds
Exit Code: 0
Stdout:
Stderr:

• Failure [3.534 seconds]
Update CPU constraints
/home/gaby/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:401
  Update number of CPUs to check period and quota
  /home/gaby/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table.go:96
    quota/period should be equal to 0.5 [It]
    /home/gaby/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46

    Expected
        <int>: 255
    to be zero-valued

    /home/gaby/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:359
------------------------------
Update CPU constraints Update number of CPUs to check period and quota
  quota/period should be equal to 1.0
  /home/gaby/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46
Running command '/usr/bin/docker [docker run --runtime kata-runtime --rm --name QAS4zDax9mR649ONWFCpXO1oZu0UFS -dt debian bash]'
[docker run --runtime kata-runtime --rm --name QAS4zDax9mR649ONWFCpXO1oZu0UFS -dt debian bash]
Timeout: 5 seconds
Exit Code: 0
Stdout: 0a09b5a01f3441e722e26ff2335424cf52618a4d95fbc0607b232eb64b1a6b75

Stderr:
Running command '/usr/bin/docker [docker update --cpus 1.000000 QAS4zDax9mR649ONWFCpXO1oZu0UFS]'
[docker update --cpus 1.000000 QAS4zDax9mR649ONWFCpXO1oZu0UFS]
Timeout: 5 seconds
Exit Code: 0
Stdout: QAS4zDax9mR649ONWFCpXO1oZu0UFS

Stderr:
Running command '/usr/bin/docker [docker exec QAS4zDax9mR649ONWFCpXO1oZu0UFS bash -c perl -e "printf ('%.1f', $(cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us)/$(cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_period_us))"]'
command failed error 'exit status 255'
[docker exec QAS4zDax9mR649ONWFCpXO1oZu0UFS bash -c perl -e "printf ('%.1f', $(cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us)/$(cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_period_us))"]
Timeout: 5 seconds
Exit Code: 255
Stdout:
Stderr: cat: /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us: No such file or directory
cat: /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_period_us: No such file or directory
Search pattern not terminated at -e line 1.

Running command '/usr/bin/docker [docker rm -f QAS4zDax9mR649ONWFCpXO1oZu0UFS]'
[docker rm -f QAS4zDax9mR649ONWFCpXO1oZu0UFS]
Timeout: 5 seconds
Exit Code: 0
Stdout: QAS4zDax9mR649ONWFCpXO1oZu0UFS

Stderr:
Running command '/usr/bin/docker [docker ps -a -f name=QAS4zDax9mR649ONWFCpXO1oZu0UFS --format {{.Status}}]'
[docker ps -a -f name=QAS4zDax9mR649ONWFCpXO1oZu0UFS --format {{.Status}}]
Timeout: 5 seconds
Exit Code: 0
Stdout:
Stderr:

• Failure [3.540 seconds]
Update CPU constraints
/home/gaby/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:401
  Update number of CPUs to check period and quota
  /home/gaby/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table.go:96
    quota/period should be equal to 1.0 [It]
    /home/gaby/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46

    Expected
        <int>: 255
    to be zero-valued

    /home/gaby/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:359
------------------------------
Update CPU constraints Update number of CPUs to check period and quota
  quota/period should be equal to 1.2
  /home/gaby/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46
Running command '/usr/bin/docker [docker run --runtime kata-runtime --rm --name DXYJRRr9QD7GgNwGqA3SiRqe4dvLjE -dt debian bash]'
[docker run --runtime kata-runtime --rm --name DXYJRRr9QD7GgNwGqA3SiRqe4dvLjE -dt debian bash]
Timeout: 5 seconds
Exit Code: 0
Stdout: 1b8ae62bab2bbff8b48d9e907e210d01c060249add7e934c5c775a04d5a5d0f8

Stderr:
Running command '/usr/bin/docker [docker update --cpus 1.200000 DXYJRRr9QD7GgNwGqA3SiRqe4dvLjE]'
[docker update --cpus 1.200000 DXYJRRr9QD7GgNwGqA3SiRqe4dvLjE]
Timeout: 5 seconds
Exit Code: 0
Stdout: DXYJRRr9QD7GgNwGqA3SiRqe4dvLjE

Stderr:
Running command '/usr/bin/docker [docker exec DXYJRRr9QD7GgNwGqA3SiRqe4dvLjE bash -c perl -e "printf ('%.1f', $(cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us)/$(cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_period_us))"]'
command failed error 'exit status 255'
[docker exec DXYJRRr9QD7GgNwGqA3SiRqe4dvLjE bash -c perl -e "printf ('%.1f', $(cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us)/$(cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_period_us))"]
Timeout: 5 seconds
Exit Code: 255
Stdout:
Stderr: cat: /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us: No such file or directory
cat: /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_period_us: No such file or directory
Search pattern not terminated at -e line 1.

Running command '/usr/bin/docker [docker rm -f DXYJRRr9QD7GgNwGqA3SiRqe4dvLjE]'
[docker rm -f DXYJRRr9QD7GgNwGqA3SiRqe4dvLjE]
Timeout: 5 seconds
Exit Code: 0
Stdout: DXYJRRr9QD7GgNwGqA3SiRqe4dvLjE

Stderr:
Running command '/usr/bin/docker [docker ps -a -f name=DXYJRRr9QD7GgNwGqA3SiRqe4dvLjE --format {{.Status}}]'
[docker ps -a -f name=DXYJRRr9QD7GgNwGqA3SiRqe4dvLjE --format {{.Status}}]
Timeout: 5 seconds
Exit Code: 0
Stdout:
Stderr:
```

The main error is that these files do not exist
```
/sys/fs/cgroup/cpu,cpuacct/cpu.cfs_period_us: No such file or directory
```

### PR DESCRIPTION
**Pull request by devimc**
When agent runs as init process cgroup fs is mounted at /proc,
OnlineCPUMem must be able to support both paths, /proc and /sys/fs.

fixes #262

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by devimc** [comment]
see https://github.com/kata-containers/agent/commit/1e72fbbe08ebfa8c457d270fbe63ee5b56e222c3

File: grpc.go [hunk 1]
```diff
@@ -56,7 +56,7 @@ var (
 	sysfsCPUOnlinePath     = "/sys/devices/system/cpu"
 	sysfsMemOnlinePath     = "/sys/devices/system/memory"
 	sysfsConnectedCPUsPath = filepath.Join(sysfsCPUOnlinePath, "online")
-	sysfsCpusetPath        = "/sys/fs/cgroup/cpuset"
+	sysfsCpusetPath        = cgroupPath + "/cpuset"
```
Comment (sboeuf) [inline grpc.go]: Does this work ? I mean in case of the agent is run as init, do you actually get `sysfdCpusetPath` containing the value `/proc/cgroup/cpuset` ?
I am asking because I thought the process would load every global variable in memory, meaning that at this time, it would have `cgroupPath = "/sys/fs/cgroup"` and therefore `sysfsCpusetPath = "/sys/fs/cgroup/cpuset"`.
My understanding is that `initAgentAsInit()` will get called later and the modification of the variable will only affect `cgroupPath`, but `sysfsCpusetPath` will remain unchanged.

Comment (devimc) [reply grpc.go]: yep it works, maybe because `initAgentAsInit` is called before using any function in `grpc.go`
I need to change this since this is not a good way to initialize a variable
good catch! thanks

**Comment by bergwolf** [comment]
lgtm!

**Comment by bergwolf** [comment]
ubuntu 16-04 failure is unrelated. Merge regardlessly sincee centos-7-4 and fedora-27 both passed.
