### PR TITLE
agent: support agent as init process in rootfs images

### LINKED ISSUE #264: consider allowing agent to run as PID 1 in systemd-based rootfs images
Currently, if you build a rootfs using `AGENT_INIT=yes` using an initrd distro (such as centos), the agent will fail at startup as it cannot mount `/dev` (as it's already mounted).

We could consider adding a magic `agent.no-dev-mount=true` kernel command-line option to allow us to test the agent as PID 1 in rootfs images other than alpine.

wdyt @bergwolf?

### PR DESCRIPTION
**Pull request by devimc**
Don't fail if `dev` is already mounted

fixes #264

cc @jodh-intel @bergwolf 

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

File: agent.go [hunk 1]
```diff
@@ -847,7 +847,9 @@ func mountToRootfs(m initMount) error {
 func generalMount() error {
 	for _, m := range initRootfsMounts {
 		if err := mountToRootfs(m); err != nil {
-			return err
+			// Don't fail and try to mount the rest of filesystems
+			agentLog.Warnf("Could not mount %v: %v", m.src, err)
```
Comment (bergwolf) [inline agent.go]: If we are sure `/dev` is the only exception, can you filter it out and still fail for all the other cases?

**Comment by grahamwhaley** [comment]
CI saw some net timeout - but not nudging, as I'm predicting there will be an update/repush which will trigger a CI re-run.

**Comment by devimc** [comment]
@jodh-intel @bergwolf  changes applied, thanks

**Comment by jodh-intel** [comment]
lgtm

**Comment by bergwolf** [comment]
`02:33:20 ERROR: command perf not available`

metrics CI is broken today and the issue is tracked at https://github.com/kata-containers/tests/issues/763. Let's ignore it and merge the PR.
