### PR TITLE
agent: judge whether /sys/devices/system/memory/block_size_bytes exist.

### LINKED ISSUE #394: open /sys/devices/system/memory/block_size_bytes: no such file or directory
# Description of problem
run a kata container with a kernel compiled before

# Expected result

setup successfully

# Actual result

setup container failed: 
```docker: Error response from daemon: oci runtime error: rpc error: code = Unknown desc = open /sys/devices/system/memory/block_size_bytes: no such file or directory.```

---

### PR DESCRIPTION
**Pull request by clarecch**
/sys/devices/system/memory/block_size_bytes will not exist when guestos
doesn't support memory hotplug. Add judgement when file
/sys/devices/system/memory/block_size_bytes doesn't exist.

Fixes #394

Signed-off-by: Clare Chen <clare.chenhui@huawei.com>

### CODE REVIEW

File: grpc.go [hunk 1]
```diff
@@ -1320,13 +1321,18 @@ func (a *agentGRPC) ReseedRandomDev(ctx context.Context, req *pb.ReseedRandomDev
...
 	var details pb.GuestDetailsResponse
 	if req.MemBlockSize {
-		data, err := ioutil.ReadFile("/sys/devices/system/memory/block_size_bytes")
-		if err != nil {
-			return nil, err
-		}
-		details.MemBlockSizeBytes, err = strconv.ParseUint(string(data[:len(data)-1]), 16, 64)
-		if err != nil {
-			return nil, err
+		if _, err := os.Stat(sysfsMemoryBlockSizePath); err != nil {
```
Comment (jodh-intel) [inline grpc.go]: This code can be simplified - rather than calling `os.Stat()`, just call the `ioutil.ReadFile()`. If an error is returned, check it with [`IsNotExist`](https://golang.org/pkg/os/#IsNotExist).

Also, I think it would be useful if you define a global `var` for `/sys/devices/system/memory/block_size_bytes` (or maybe find a way to pass the file to test as a function arg) as that would allow you to update the test in  `TestGetGuestDetails` to handle both scenarios.

Comment (clarecch) [reply grpc.go]: > Also, I think it would be useful if you define a global `var` for `/sys/devices/system/memory/block_size_bytes` (or maybe find a way to pass the file to test as a function arg) as that would allow you to update the test in `TestGetGuestDetails` to handle both scenarios.

Yes, I have defined a global variable `sysfsMemoryBlockSizePath` for `/sys/devices/system/memory/block_size_bytes`, and update the test. Is that what you mean?

Comment (jodh-intel) [reply grpc.go]: Hi @clarecch - partly. Now that you have that path stored in a variable, the test can change the value so you can test the following scenarios:

- When the file does not exist.
- When the file exists and contains data in the correct format for `ParseUint()`.
- When the file exists and contains data in an invalid format for `ParseUint()`

  You could just write `hello world` to a tempfile and assign `sysfsMemoryBlockSizePath` to that tempfile for example. Yes, this is paranoia ;)

But also note my comment - you do not need a call to `os.Stat()` at all I believe.

Comment (clarecch) [reply grpc.go]: Thanks for explanation @jodh-intel

**Comment by clarecch** [comment]
Updated, PTAL

File: grpc.go [hunk 2]
```diff
@@ -1320,13 +1321,22 @@ func (a *agentGRPC) ReseedRandomDev(ctx context.Context, req *pb.ReseedRandomDev
...
-			return nil, err
+			if os.IsNotExist(err) {
+				agentLog.WithField("sysfsMemoryBlockSizePath", sysfsMemoryBlockSizePath).Error("Guest kernel config doesn't support memory hotplug")
+				details.MemBlockSizeBytes = 0
+			} else {
+				return nil, err
+			}
+		} else {
+			if len(data) == 0 {
+				return nil, fmt.Errorf("/sys/devices/system/memory/block_size_bytes is empty")
```
Comment (jodh-intel) [inline grpc.go]: Could you use `sysfsMemoryBlockSizePath` in the error rather than hard-coding the path?

Comment (clarecch) [reply grpc.go]: ok, updated

**Comment by jodh-intel** [comment]
Thanks @clarecch!

ping @sboeuf.

File: grpc.go [hunk 3]
```diff
@@ -1320,13 +1321,22 @@ func (a *agentGRPC) ReseedRandomDev(ctx context.Context, req *pb.ReseedRandomDev
...
-		data, err := ioutil.ReadFile("/sys/devices/system/memory/block_size_bytes")
+		data, err := ioutil.ReadFile(sysfsMemoryBlockSizePath)
 		if err != nil {
-			return nil, err
-		}
-		details.MemBlockSizeBytes, err = strconv.ParseUint(string(data[:len(data)-1]), 16, 64)
-		if err != nil {
-			return nil, err
+			if os.IsNotExist(err) {
+				agentLog.WithField("sysfsMemoryBlockSizePath", sysfsMemoryBlockSizePath).Error("Guest kernel config doesn't support memory hotplug")
```
Comment (sboeuf) [inline grpc.go]: This should be an `Info` log, not an `Error` one IMO.

File: grpc.go [hunk 4]
```diff
@@ -1320,13 +1321,22 @@ func (a *agentGRPC) ReseedRandomDev(ctx context.Context, req *pb.ReseedRandomDev
...
+				details.MemBlockSizeBytes = 0
```
Comment (sboeuf) [inline grpc.go]: No need for this, the default value for `MemBlockSizeBytes` from the structure `pb.GuestDetailsResponse` will be 0.

Comment (clarecch) [reply grpc.go]: Thanks @sboeuf , it's reasonable, updated.

**Comment by sboeuf** [comment]
Thanks @clarecch LGTM!

File: grpc.go [hunk 5]
```diff
@@ -1320,13 +1321,21 @@ func (a *agentGRPC) ReseedRandomDev(ctx context.Context, req *pb.ReseedRandomDev
...
-		data, err := ioutil.ReadFile("/sys/devices/system/memory/block_size_bytes")
+		data, err := ioutil.ReadFile(sysfsMemoryBlockSizePath)
 		if err != nil {
-			return nil, err
-		}
-		details.MemBlockSizeBytes, err = strconv.ParseUint(string(data[:len(data)-1]), 16, 64)
-		if err != nil {
-			return nil, err
+			if os.IsNotExist(err) {
+				agentLog.WithField("sysfsMemoryBlockSizePath", sysfsMemoryBlockSizePath).Info("Guest kernel config doesn't support memory hotplug")
```
Comment (bergwolf) [inline grpc.go]: Do you have a counter part PR to the runtime repo that handles zero memory block size returned by the agent?

**Comment by clarecch** [comment]
Why is this CI still pending?

File: grpc.go (hunk 5 above)
Comment (bergwolf) [reply grpc.go]: nice!

**Comment by bergwolf** [comment]
LGTM

**Comment by grahamwhaley** [comment]
Hi @clarecch - CI was pending as we recently moved from an 'always run CI' to an 'on demand CI' flow. Thanks to @bergwolf for issuing the test command. @chavafg , one thing that worries me a touch is that 6h after the CI request was issued, those jobs still look to be 'triggered and pending'.

**Comment by amshinde** [comment]
Rerunning fedora job.

**Comment by clarecch** [comment]
The CI fedora fail with this for many times. Is there something wrong caused by me?
```
/tmp/jenkins/workspace/kata-containers-agent-fedora-27-PR/go/src/github.com/kata-containers/tests
time="2018-10-09T06:29:21Z" level=info msg="CPU property found" arch=amd64 description="Intel Architecture CPU" name=GenuineIntel pid=11262 source=runtime type=attribute
time="2018-10-09T06:29:21Z" level=info msg="CPU property found" arch=amd64 description="64Bit CPU" name=lm pid=11262 source=runtime type=flag
time="2018-10-09T06:29:21Z" level=info msg="CPU property found" arch=amd64 description=SSE4.1 name=sse4_1 pid=11262 source=runtime type=flag
time="2018-10-09T06:29:21Z" level=error msg="CPU property not found" arch=amd64 description="Virtualization support" name=vmx pid=11262 source=runtime type=flag
time="2018-10-09T06:29:21Z" level=info msg="kernel property found" arch=amd64 description="Kernel-based Virtual Machine" name=kvm pid=11262 source=runtime type=module
time="2018-10-09T06:29:21Z" level=info msg="kernel property found" arch=amd64 description="Host kernel accelerator for virtio" name=vhost pid=11262 source=runtime type=module
time="2018-10-09T06:29:21Z" level=info msg="kernel property found" arch=amd64 description="Host kernel accelerator for virtio network" name=vhost_net pid=11262 source=runtime type=module
time="2018-10-09T06:29:21Z" level=info msg="kernel property found" arch=amd64 description="Intel KVM" name=kvm_intel pid=11262 source=runtime type=module
time="2018-10-09T06:29:21Z" level=error msg="open /sys/module/kvm_intel/parameters/nested: no such file or directory" arch=amd64 name=kata-runtime pid=11262 source=runtime
open /sys/module/kvm_intel/parameters/nested: no such file or directory
Build step 'Execute shell' marked build as failure
Performing Post build task...
Match found for :.* : True
Logical operation result is TRUE
Running script  : #!/bin/bash
```

**Comment by caoruidong** [comment]
Some jenkins lost nested virtualization. Not your problem

**Comment by clarecch** [comment]
Thanks for explanation @caoruidong

**Comment by clarecch** [comment]
The CI is green now, PTAL

**Comment by jodh-intel** [comment]
\o/ Thanks @clarecch.
