### PR TITLE
agent: disable yamux keep alive

### LINKED ISSUE #294: yamux: keepalive failed: i/o deadline reached for proxybuiltin
# Description of problem

When kata is integrated into hyper, which uses the proxybuiltin mode. 
Once do  hyperctl pause <pod id>, which will pause the sandbox. 
After pause about 30s, builtin proxy will complain of "yamux: keepalive failed: i/o deadline reached"

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

---

(replace this text with the output of the `kata-collect-data.sh` script, after
you have reviewed its content to ensure it does not contain any private
information).

### PR DESCRIPTION
**Pull request by lifupan**
We don't know how much time a sandbox can be paused,
hence connection write timeout should be disabled to
don't close the connection while the sandbox is paused.

The same issue has been fixed in kata-proxy, for katabuiltin proxy,
it also needs this fix.

fixes #294

Signed-off-by: fupan <lifupan@gmail.com>

### CODE REVIEW

File: protocols/client/client.go [hunk 1]
```diff
@@ -147,7 +147,10 @@ func agentDialer(addr *url.URL, enableYamux bool) dialer {
 		}()
 
 		var session *yamux.Session
-		session, err = yamux.Client(conn, nil)
+		sessionConfig := yamux.DefaultConfig()
+		// Disable keepAlive since we don't know how much time a container can be paused
+		sessionConfig.EnableKeepAlive = false
+		session, err = yamux.Client(conn, sessionConfig)
```
Comment (jodh-intel) [inline protocols/client/client.go]: As you are now passing config to the client api, you might want to set `sessionConfig.LogOutput`, similar to #289, so that any yamux warnings+errors are logged to the agent log?

Comment (lifupan) [reply protocols/client/client.go]: Hi, Jodh

Here the yamux client is running in the buildin proxy, instead of agent context, and there is no logger instance here.

Comment (jodh-intel) [reply protocols/client/client.go]: ah - ok. So do you not get any agent logs then?

Comment (bergwolf) [reply protocols/client/client.go]: No, this is consumed by the runtime instead.

**Comment by bergwolf** [comment]
LGTM!

**Comment by devimc** [comment]
lgtm

Just waiting for the CI

**Comment by amshinde** [comment]
CI seems to be failing due to error downloading `alpine` docker image. Have restarted the CI jobs.

**Comment by bergwolf** [comment]
Ignore `jenkins-ci-ubuntu-16-04-initrd` failure since that is expected to pass only after we merge #297
