### PR TITLE
client: do cleanup after UT stop mock server

### LINKED ISSUE #418: fails when make test twice as non-root user
# Description of problem
When I execute `make test` twice, I got an error.
> [ningbo@localhost agent]$ export KATA_DEV_MODE=true
> [ningbo@localhost agent]$ make test >1.log && (make test >2.log || echo "make test 2nd time failed") || echo "make test 1st time failed"
> make: *** [test] Error 1
> make test 2nd time failed

# Cause
It's easy to reproduce

> [ningbo@localhost agent]$ export KATA_DEV_MODE=true
> [ningbo@localhost agent]$ sudo touch /tmp/agentserver.sock
> [ningbo@localhost agent]$ /usr/bin/go test -timeout 30s github.com/kata-containers/agent/protocols/client -run ^TestNewAgentClient$
> panic: runtime error: invalid memory address or nil pointer dereference
>         panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7e57fd]
> 
> goroutine 7 [running]:
> github.com/kata-containers/agent/vendor/google.golang.org/grpc.(*Server).Serve.func2(0xc0001091e0, 0x0, 0x0)
>         /home/ningbo/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/server.go:494 +0xad
> panic(0x96f440, 0xea7f10)
>         /usr/lib/go1.11.1/src/runtime/panic.go:513 +0x1b9
> github.com/kata-containers/agent/vendor/google.golang.org/grpc.(*Server).Serve(0xc0001091e0, 0x0, 0x0, 0x0, 0x0)
>         /home/ningbo/go/src/github.com/kata-containers/agent/vendor/google.golang.org/grpc/server.go:503 +0x1bb
> github.com/kata-containers/agent/protocols/client.startMockServer.func1(0xc000082660, 0x0, 0x0, 0x0, 0xc00016e100, 0xc0001091e0)
>         /home/ningbo/go/src/github.com/kata-containers/agent/protocols/client/client_test.go:59 +0x78
> created by github.com/kata-containers/agent/protocols/client.startMockServer
>         /home/ningbo/go/src/github.com/kata-containers/agent/protocols/client/client_test.go:48 +0x1b8
> FAIL    github.com/kata-containers/agent/protocols/client       0.005s

The test case will be run as current(non-root) user then root user when execute `make test`.
`/tmp/agentserver.agent`(owner is root now) will exists in system after the 1st time, it will fail when remove the file as non-root user at 2nd time.

# Solution
remove `/tmp/agentserver.agent` when test case is done and output friendly error message when failed.

### PR DESCRIPTION
**Pull request by BetaXOi**
Remove `/tmp/agentserver.socker` when test case is done and output firendly error message when remove the file failed.

Fixes #418

Signed-off-by: NingBo <ning.bo9@zte.com.cn>

### CODE REVIEW

File: protocols/client/client_test.go [hunk 1]
```diff
@@ -132,6 +136,7 @@ func TestNewAgentClient(t *testing.T) {
 	// wait mock server to stop
 	mock.Stop()
 	<-waitCh
+	os.Remove(mockSockAddr)
```
Comment (jodh-intel) [inline protocols/client/client_test.go]: Nit: This call (and the one below) could be put into a `defer` and moved to just below the error check after calling `startMockServer()`.

**Comment by jodh-intel** [comment]
Good catch! And we like friendly messages :smile:

lgtm

/test

File: protocols/client/client_test.go (hunk 1 above)
Comment (BetaXOi) [reply protocols/client/client_test.go]: Fixed, thank you.

**Comment by jodh-intel** [comment]
Thanks @BetaXOi!

lgtm

/test

**Comment by jodh-intel** [comment]
Re-started the 16.04 CI which got wedged on what looks like an external net connectivity issue:

```
not ok 1 Verify nginx connectivity between pods
# (from function `setup' in test file nginx.bats, line 19)
#   `sudo -E crictl pull "$nginx_image"' failed
# Image is up to date for docker.io/library/busybox@sha256:915f390a8912e16d4beb8689720a17348f3f6d1a7b659697df850ab625ea29d5
# time="2018-11-30T02:38:08Z" level=fatal msg="pulling image failed: rpc error: code = Unknown desc = Error writing blob: error storing blob to file \"/var/tmp/storage826968591/2\": read tcp 10.0.0.9:47454->104.18.125.25:443: read: connection reset by peer"
# Error from server (NotFound): deployments.extensions "nginx-deployment" not found
# Error from server (NotFound): services "nginx-deployment" not found
# error: resource name may not be empty
Makefile:69: recipe for target 'kubernetes' failed
```

**Comment by bergwolf** [comment]
lgtm, thanks @BetaXOi !
