### PR TITLE
agent: increase the number of tries to online vcpus

### LINKED ISSUE #474: tests: cpu hotplug test fail randomly
seems like cpu hotplug tests are failing because 1 second is not enough to online vcpus

### PR DESCRIPTION
**Pull request by devimc**
cpu hotplug tests fail randomly in nested environments because 1 second is
not enough for the kernel and qemu to allocate and connect the vcpus.

fixes #474

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

File: grpc.go [hunk 1]
```diff
@@ -68,7 +68,7 @@ var emptyResp = &gpb.Empty{}
 
 const onlineCPUMemWaitTime = 100 * time.Millisecond
 
-const onlineCPUMaxTries = 10
+const onlineCPUMaxTries = 30
```
Comment (sboeuf) [inline grpc.go]: Why not extend it to some round and large value? Something like `100` :)

Comment (grahamwhaley) [reply grpc.go]: I probably agree - unless we have some hard deadline we know we should meet, then presumably we are looking for vcpus 'never coming online', in which case a large timeout costs us nothing apart from in the interesting rare failure case that we are looking for.
To note, I have seen 'slow' machines take >3s to get to the workload - now I don't know where that time was spent (or if it was related to entropy or not, but I think not)... so I like the idea of `100` more than `30` :-)

Comment (devimc) [reply grpc.go]: 10 seconds? :thinking:  ...  sounds good

**Comment by devimc** [comment]
@sboeuf @grahamwhaley  change applied, thanks

**Comment by amshinde** [comment]
@devimc CI is failing. ptal.

**Comment by devimc** [comment]
@amshinde fixed, thanks

**Comment by jodh-intel** [comment]
Thanks @devimc!
