### PR TITLE
agent: Rollback properly when container creation fails

### LINKED ISSUE #195: Properly rollback when container creation fails
We need to make sure the mounts performed during the container creation are completely removed in case of a failure.

### PR DESCRIPTION
**Pull request by sboeuf**
In case the container creation fails, we need a proper rollback
regarding the mounts previously performed.

Fixes #195

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
@egernst @bergwolf PTAL

**Comment by devimc** [comment]
lgtm

**Comment by sboeuf** [comment]
@laijs @bergwolf PTAL

File: grpc.go [hunk 1]
```diff
@@ -359,6 +359,27 @@ func (a *agentGRPC) CreateContainer(ctx context.Context, req *pb.CreateContainer
...
+	// Make sure we rollback the mounts performed in case the container
+	// creation failed.
+	defer func() {
+		if err != nil {
+			if ctr.container != nil {
+				ctr.container.Destroy()
+			}
+
+			a.sandbox.deleteContainer(req.ContainerId)
+			removeMounts(ctr.mounts)
```
Comment (jodh-intel) [inline grpc.go]: Shouldn't that be:

```
err = removeMounts(ctr.mounts)
```

Comment (sboeuf) [reply grpc.go]: Well not really since I don't think an error from the rollback part executed from `defer` should not gate anything.

Comment (jodh-intel) [reply grpc.go]: We're already in the error path but we should probably atleast combine the errors so they get logged at a higher level since we don't expect.

Comment (sboeuf) [reply grpc.go]: This looks overkill to me... We're already into the error path, meaning an error is going to be logged, but you also want the potential error of the error ? What should I log ? A `Debug()` one ?

Comment (jodh-intel) [reply grpc.go]: I can see that point of view and I also see that it's going to complicate the code a little, but why are we doing rollback? Answer: to ensure we *undo* the operations the agent just performed.. So we shouldn't fully ignore operations that return errors imho as that would hide bugs relating to the undo.

As a minimum, I think we should do something like:

```
err2 := removeMounts(ctr.mounts)
if err2 != nil {
    agentLog.WithError(err2).Error("rollback failed")
}
```

That way atleast we get something useful in the logs.

btw, the naming is a little random - it's not very obvious at first glance that the `defer` basically undoes `addStorages()`. Maybe the code block could be put into a `removeStorages()` to make that clearer?

Comment (sboeuf) [reply grpc.go]: Yeah makes sense, let me rework a little bit

**Comment by sboeuf** [comment]
@jodh-intel PR updated.

**Comment by jodh-intel** [comment]
lgtm

File: grpc.go [hunk 2]
```diff
@@ -359,6 +378,18 @@ func (a *agentGRPC) CreateContainer(ctx context.Context, req *pb.CreateContainer
...
 
+	ctr := &container{
+		id:        req.ContainerId,
+		processes: make(map[string]*process),
+		mounts:    mountList,
+	}
+
+	a.sandbox.setContainer(req.ContainerId, ctr)
+
+	// Make sure we rollback the mounts performed in case the container
```
Comment (grahamwhaley) [inline grpc.go]: it's not just the mounts - it is 'anything that needs undoing' (and we do a touch more cleanup there I think).

File: grpc.go [hunk 3]
```diff
@@ -388,32 +419,22 @@ func (a *agentGRPC) CreateContainer(ctx context.Context, req *pb.CreateContainer
...
-	}
-
-	a.sandbox.setContainer(req.ContainerId, container)
-
-	if err := a.execProcess(container, container.initProcess, true); err != nil {
+	if err = a.execProcess(ctr, ctr.initProcess, true); err != nil {
 		return emptyResp, err
 	}
 
-	return emptyResp, a.postExecProcess(container, container.initProcess)
```
Comment (grahamwhaley) [inline grpc.go]: doing this little rename cleanup in a separate commit would have made review a touch easier ;-)

File: grpc.go (hunk 2 above)
Comment (sboeuf) [reply grpc.go]: let me change this

Comment (sboeuf) [reply grpc.go]: done

**Comment by jodh-intel** [comment]
lgtm.

I guess we'll need to test this via https://github.com/kata-containers/tests somehow.

**Comment by sboeuf** [comment]
Can we merge this even with this codecov red cross ? I am not sure how I can add unit testing for this.

**Comment by jodh-intel** [comment]
I say yes as we haven't checked the results coming back from codecov yet (nor have we looked at thresholds).
