### PR TITLE
agent: don't receive signals from stdin

### LINKED ISSUE #746: agent can be killed through qemu's console.sock
# Description of problem

1.- Run a container
2.- Attach to the container's console.sock using socat
3.-  The agent in the guest dies and the container gets stuck

This issue is reproducible with docker and podman (rootless)

```
$ docker run --runtime=kata-runtime -dti --rm fedora bash
b39943ca919df85dfef89f90d32f8a1c2316d2f1277b23f3e4ac3a5ae58e46e7
$ sudo socat stdin,raw,echo=0,escape=0x11 unix-connect:"$(ps aux | grep qemu | grep -o -e "/run/vc/vm/[[:alnum:]]*/console.sock")"
^C[   18.434486] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000200
[   18.434486] 
[   18.435749] CPU: 0 PID: 34 Comm: kata-agent Not tainted 4.19.75 #1
[   18.436770] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.12.1-0-ga5cab58e9a3f-prebuilt.qemu.org 04/01/2014
[   18.438089] Call Trace:
[   18.438089]  dump_stack+0x5c/0x80
[   18.438089]  panic+0xd2/0x214
[   18.438089]  do_exit.cold+0x1a/0x8c
[   18.438089]  do_group_exit+0x2e/0xa0
[   18.438089]  get_signal+0x11b/0x6c0
[   18.438089]  ? do_futex+0x15e/0xc60
[   18.438089]  ? __switch_to_asm+0x41/0x70
[   18.438089]  do_signal+0x31/0x5a0
[   18.438089]  ? __switch_to_asm+0x41/0x70
[   18.438089]  ? __switch_to_asm+0x35/0x70
[   18.438089]  ? __switch_to_asm+0x41/0x70
[   18.438089]  ? __switch_to_asm+0x35/0x70
[   18.438089]  ? __switch_to_asm+0x41/0x70
[   18.438089]  ? __switch_to_asm+0x35/0x70
[   18.438089]  ? __switch_to_asm+0x41/0x70
[   18.438089]  ? __switch_to_asm+0x35/0x70
[   18.438089]  ? __switch_to_asm+0x35/0x70
[   18.438089]  ? __switch_to_asm+0x41/0x70
[   18.438089]  ? __switch_to_asm+0x35/0x70
[   18.438089]  ? __switch_to_asm+0x41/0x70
[   18.438089]  ? __switch_to_asm+0x35/0x70
[   18.438089]  ? __switch_to+0x12d/0x340
[   18.438089]  ? __x64_sys_futex+0x131/0x14a
[   18.438089]  exit_to_usermode_loop+0x87/0xa0
[   18.438089]  do_syscall_64+0x28f/0x301
[   18.438089]  ? __switch_to_asm+0x41/0x70
[   18.438089]  ? do_page_fault+0x2f/0x79
[   18.438089]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[   18.438089] RIP: 0033:0x55939521c393
[   18.438089] Code: Bad RIP value.
[   18.438089] RSP: 002b:00007fe19981bd10 EFLAGS: 00000246 ORIG_RAX: 00000000000000ca
[   18.438089] RAX: fffffffffffffdfc RBX: 0000000000000000 RCX: 000055939521c393
[   18.438089] RDX: 0000000000000000 RSI: 0000000000000080 RDI: 0000559396374390
[   18.438089] RBP: 00007fe19981bd58 R08: 0000000000000000 R09: 0000000000000000
[   18.438089] R10: 00007fe19981bd48 R11: 0000000000000246 R12: 0000000000000030
[   18.438089] R13: 0000000000000011 R14: 0000559395a31fb0 R15: 0000000000000000
[   18.438089] Kernel Offset: disabled
[   18.438089] Rebooting in 1 seconds..
[    0.380879] brd: module loaded
[    0.381689] loop: module loaded
[    0.384913]  pmem0: p1
[    0.385508] pmem0: detected capacity change from 0 to 266338304
[    0.386418] random: fast init done
[    0.392871] scsi host0: Virtio SCSI HBA
[    0.393704] random: crng init done
[    0.424059] xt_time: kernel timezone is -0000
[    0.424738] IPVS: Registered protocols (TCP, UDP, SCTP, AH, ESP)
[    0.425342] IPVS: Connection hash table configured (size=4096, memory=64Kbytes)
[    0.425806] IPVS: ipvs loaded.
[    0.426003] IPVS: [rr] scheduler registered.
[    0.426242] IPVS: [wrr] scheduler registered.
[    0.426527] IPVS: [lc] scheduler registered.
[    0.426715] IPVS: [wlc] scheduler registered.
[    0.426935] IPVS: [fo] scheduler registered.
[    0.427135] IPVS: [ovf] scheduler registered.
[    0.427401] IPVS: [lblc] scheduler registered.
[    0.427603] IPVS: [lblcr] scheduler registered.
[    0.427790] IPVS: [dh] scheduler registered.
[    0.427975] IPVS: [sh] scheduler registered.
[    0.428293] IPVS: [sed] scheduler registered.
[    0.428542] IPVS: [nq] scheduler registered.
[    0.428785] IPVS: ftp: loaded support on port[0] = 21
[    0.428992] IPVS: [sip] pe registered.
[    0.429273] ipt_CLUSTERIP: ClusterIP Version 0.8 loaded successfully
[    0.429613] Initializing XFRM netlink socket
[    0.429944] NET: Registered protocol family 10
[    0.431076] Segment Routing with IPv6
[    0.431322] NET: Registered protocol family 17
[    0.431804] 9pnet: Installing 9P2000 support
[    0.436044] NET: Registered protocol family 40
[    0.437270] EXT4-fs (pmem0p1): DAX enabled. Warning: EXPERIMENTAL, use at your own risk
[    0.440040] EXT4-fs (pmem0p1): mounted filesystem with ordered data mode. Opts: dax,data=ordered,errors=remount-ro
[    0.440797] VFS: Mounted root (ext4 filesystem) readonly on device 259:1.
[    0.441724] devtmpfs: mounted
[    0.446212] Freeing unused kernel image memory: 856K
[    0.452408] Write protecting the kernel read-only data: 12288k
[    0.480483] Freeing unused kernel image memory: 2024K
[    0.480903] Freeing unused kernel image memory: 808K
[    0.481225] Run /usr/bin/kata-agent as init process
WARN[0000] Could not mount filesystem                    error="rpc error: code = Internal desc = Could not mount dev to /dev: device or resource busy" name=kata-agent pid=1 source=agent src=dev
announce: pid="1",source="agent",name="kata-agent",version="1.11.0-alpha0-d26a505efd336e966636f9aa30eaacd29cf8a58f-dirty",device-handlers="scsi,nvdimm,mmioblk,blk,blk-ccw",storage-handlers="virtio-fs,blk,blk-ccw,mmioblk,scsi,ephemeral,local,9p",system-memory="2044472 kB"
announce: name="kata-agent",pid="1",source="agent",version="1.11.0-alpha0-d26a505efd336e966636f9aa30eaacd29cf8a58f-dirty",device-handlers="mmioblk,blk,blk-ccw,scsi,nvdimm",storage-handlers="blk-ccw,mmioblk,scsi,ephemeral,local,9p,virtio-fs,blk",system-memory="2044472 kB"
time="2020-02-21T19:41:22.121946125Z" level=debug msg="Serial channel type detected" debug_console=false name=kata-agent pid=1 source=agent
time="2020-02-21T19:41:22.125049441Z" level=info msg="Started listening for uevents" debug_console=false name=kata-agent pid=1 source=agent subsystem=udevlistener
time="2020-02-21T19:41:22.141940564Z" level=info msg="agent grpc server starts" debug_console=false name=kata-agent pid=1 source=agent
time="2020-02-21T19:41:22.143698108Z" level=debug msg="New serial channel event" debug_console=false events=4 name=kata-agent pid=1 source=agent
time="2020-02-21T19:41:22.146457202Z" level=info msg="Waiting for stopServer signal..." debug_console=false name=kata-agent pid=1 source=agent subsystem=stopserverwatcher
```

# Expected result

agent shouldn't die

### PR DESCRIPTION
**Pull request by devimc**
close stdin to avoid agent be killed through the stdin

fixes #746

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
I've kicked rebuilds for F31 and bunty18 - failures looked different and possibly unrelated.

**Comment by devimc** [comment]
@grahamwhaley thanks,
centos CI still stuck :worried:

**Comment by jodh-intel** [comment]
huh? / oops! :smile:

File: agent.go [hunk 1]
```diff
@@ -1445,6 +1445,11 @@ func init() {
 		}
 		panic("--this line should have never been executed, congratulations--")
 	}
+
+	// agent won't receive anything from the stdin.
+	// Close stdin to avoid the agent receives signals
+	// (ctrl + c/d) from the stdin.
+	os.Stdin.Close()
```
Comment (jodh-intel) [inline agent.go]: Good catch @devimc ! Could you tal at the rust agent to see if we need to do the same there please?

Comment (devimc) [reply agent.go]: @jodh-intel  sure thing

Comment (devimc) [reply agent.go]: @jodh-intel I couldn't reproduce it with the rust agent

**Comment by devimc** [comment]
@jodh-intel  @grahamwhaley  @amshinde  CI looks happy, can we merge this?

**Comment by amshinde** [comment]
Retriggered Centos build. @GabyCT is there an issue with Centos build?

**Comment by jodh-intel** [comment]
Centos q35 still failing with an `EPERM` issue:

```
docker build    --build-arg arch=amd64 -t katacontainers/agent-dev:e4c2037 .
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.38/build?buildargs=%7B%22arch%22%3A%22amd64%22%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=m8zcx6o8qgi1n3mjzrq2wp3n6&shmsize=0&t=katacontainers%2Fagent-dev%3Ae4c2037&target=&ulimits=null&version=1: dial unix /var/run/docker.sock: connect: permission denied
```

**Comment by jodh-intel** [comment]
Restarted once more...

**Comment by GabyCT** [comment]
@amshinde yes, Centos 8 has been instable https://github.com/kata-containers/ci/issues/249, mainly mirror issues and that causes the packages not being installed properly, I change it to use Centos 7 which is more stable
