### PR TITLE
protocols/grpc: fix CPU hotplug race condition

### LINKED ISSUE #181: CPU hotplug race condition
all vCPUs are not connected in systems running low on resources,  for example in a virtual machine with 1 vCPU + 256 MB of RAM, 

```sh
docker run -ti --runtime kata-runtime --rm --cpu-quota 30000 --cpu-period 10000 busybox sh -c "sleep 5; nproc"
```
returns 2, when the expected result is 4 (1 cold plugged vCPU + 3 hot plugged vCPUs)

### PR DESCRIPTION
**Pull request by devimc**
With this patch the runtime will communicate to the agent the
number of vCPUs that were hot added, allowing to the agent online all vCPUs.
The agent will try to online all vCPUs 5 times, waiting 500 milliseconds
in each iteration, this is needed since when the runtime calls to QMP
`device_add`, QEMU doesn't allocate all vCPUs inmediatelly.

fixes #181

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

File: grpc.go [hunk 1]
```diff
@@ -56,40 +58,85 @@ type onlineResource struct {
...
-	resourceList := []onlineResource{
-		{
-			sysfsOnlinePath: sysfsCPUOnlinePath,
-			regexpPattern:   cpuRegexpPattern,
-		},
-		{
-			sysfsOnlinePath: sysfsMemOnlinePath,
-			regexpPattern:   memRegexpPattern,
-		},
+var onlineCPUMemMux sync.Mutex
```
Comment (sboeuf) [inline grpc.go]: Looks like a multiplexer with the naming `...Mux`. Please call this `onlineCPUMemLock`

File: grpc.go [hunk 2]
```diff
@@ -56,40 +58,85 @@ type onlineResource struct {
...
+
+const onlineCPUMemWaitTime = 500 * time.Millisecond
```
Comment (sboeuf) [inline grpc.go]: This looks like a lot ! We cannot afford to wait for so much time between two retries. Something like 50ms seems more appropriate, and maybe increase the number of retries if you think that in some cases it might take some time.

File: grpc.go [hunk 3]
```diff
@@ -752,7 +799,7 @@ func (a *agentGRPC) UpdateRoutes(ctx context.Context, req *pb.UpdateRoutesReques
 }
 
 func (a *agentGRPC) OnlineCPUMem(ctx context.Context, req *pb.OnlineCPUMemRequest) (*gpb.Empty, error) {
-	go onlineCPUMem()
+	go onlineCPUMem(req)
```
Comment (sboeuf) [inline grpc.go]: I think this should not be spawned into a go routine. This is the caller responsibility to know if it should wait or not for the return of this function.
Also, if we look at this patch, we expect to be able to return a valid error in case we could not hotplug the amount of CPUs provided as parameter.

File: protocols/grpc/agent.proto [hunk 4]
```diff
@@ -187,6 +187,8 @@ message UpdateRoutesRequest {
 }
 
 message OnlineCPUMemRequest {
+	// Specify the number of CPUs that were added
+	uint32 cpus = 1;
```
Comment (sboeuf) [inline protocols/grpc/agent.proto]: Was thinking that `nb_cpus` or something with number in it, might be more appropriate as the parameter here, since we're providing a number of CPUs.

File: grpc.go [hunk 5]
```diff
@@ -56,40 +58,85 @@ type onlineResource struct {
...
+func onlineCPUMem(req *pb.OnlineCPUMemRequest) {
+	onlineCPUMemMux.Lock()
+	defer onlineCPUMemMux.Unlock()
+
+	cpuResource := onlineResource{
+		sysfsOnlinePath: sysfsCPUOnlinePath,
+		regexpPattern:   cpuRegexpPattern,
+	}
+
+	err := forceOnlineResources(cpuResource, req.Cpus, onlineCPUMaxTries)
```
Comment (sboeuf) [inline grpc.go]: Having functions `onlineCPUResources()` and `onlineMemResources()` seems more appropriate to make the code more readable.
```go
func onlineCPUResources(nbCPU int) error {
        resource := onlineResource{
		sysfsOnlinePath: sysfsCPUOnlinePath,
		regexpPattern:   cpuRegexpPattern,
	}

	var count uint32
	for i := uint32(0); i < onlineCPUMaxTries; i++ {
		r, err := onlineResources(resource)
		if err != nil {
			return err
		}
		count += r
		if count == nbCPU {
			return nil
		}
		time.Sleep(onlineCPUMemWaitTime)
	}

	return fmt.Errorf("only %d of %d were connected", count, expectedResources)
}

func onlineMemResources() error {
        resource := onlineResource{
		sysfsOnlinePath: sysfsMemOnlinePath,
		regexpPattern:   memRegexpPattern,
	}

        _, err := onlineResources(resource)
        return err
}
```

**Comment by jodh-intel** [comment]
> when the runtime calls to QMP device_add, QEMU doesn't allocate all vCPUs inmediatelly.

I think this the piece of code you're referring to:

- https://github.com/kata-containers/runtime/blob/master/virtcontainers/qemu.go#L712..L736

If so, I was about to say that QMP needs a transaction message, when -- guess what? -- I found that it already has!

- https://github.com/qemu/qemu/blob/master/qapi/transaction.json#L87..L151

Hence, we should be able to replace that loop with a call to something like:

```
{
  "execute": "transaction",                    
  "arguments": { "actions": [                  
    { 
      "type": "device_add",
      "data" : { 
        "id": "cpu-0", "socket-id": "...", "core-id": "...", "thread-id": "..." 
      }   
    },
    { 
      "type": "device_add",
      "data" : { 
        "id": "cpu-1", "socket-id": "...", "core-id": "...", "thread-id": "..." 
      }   
    },
    { 
      "type": "device_add",
      "data" : { 
        "id": "cpu-2", "socket-id": "...", "core-id": "...", "thread-id": "..." 
      }   
    } 
  ]                                            
}
```
It would be useful to have this feature in https://github.com/intel/govmm.

/cc @rarindam, @markdryan.

**Comment by markdryan** [comment]
@jodh-intel I'd never seen that transaction command before.  I'd assumed it was new when you mentioned it but looking at the qmp docs it seems to have been around since 1.0.

The way we currently model QMP commands doesn't really lend itself to a generic transaction mechanism.  Perhaps this is a sign that the API is wrong and should be changed.  In the short term it should be possible to add a ExecuteAddDevices that adds multiple devices transactionally.

The other comment I would make is, would using transactions actually solve the race condition?  Does qmp generate an event when adding a device?  Perhaps ExecuteDeviceAdd just needs to wait for that.  Modifying ExecuteDeviceAdd might be a little risky, but we could add a new blocking version of that function and migrate to it over time.

**Comment by devimc** [comment]
Hi @jodh-intel nice finding!
but I think `transactional` messages won't fix the race condition, since it only guarantee a failure if any operation fail, the problem with the race condition is that QEMU does not allocate and assign vCPUs intermediately, because it has to negotiate the resources with KVM.
For example, if 5 vCPUs are hot added to the VM, when `onlineCPUMem` is called,  probably only 3 vCPUs have been allocated and assigned to the VM, that means the agent will online only 3 vCPUs, the other two vCPUs will be allocated and assigned later, but the agent won't be able to online them.

**Comment by devimc** [comment]
@sboeuf changes applied, thanks

File: grpc.go [hunk 6]
```diff
@@ -56,40 +58,93 @@ type onlineResource struct {
...
+			continue
+		}
 
-			onlinePath := filepath.Join(resource.sysfsOnlinePath, file.Name(), "online")
+		if strings.Trim(string(status), "\n\t ") == "0" {
 			ioutil.WriteFile(onlinePath, []byte("1"), 0600)
+			count++
+		}
+
+		if nbResources != -1 && count == uint32(nbResources) {
```
Comment (sboeuf) [inline grpc.go]:
```go
if nbResources > 0 && count == uint32(nbResources) {
```

File: grpc.go [hunk 7]
```diff
@@ -56,40 +58,93 @@ type onlineResource struct {
...
+		onlinePath := filepath.Join(resource.sysfsOnlinePath, file.Name(), "online")
+		status, err := ioutil.ReadFile(onlinePath)
+		if err != nil {
+			// resource cold plugged
+			continue
+		}
 
-			onlinePath := filepath.Join(resource.sysfsOnlinePath, file.Name(), "online")
+		if strings.Trim(string(status), "\n\t ") == "0" {
 			ioutil.WriteFile(onlinePath, []byte("1"), 0600)
```
Comment (markdryan) [inline grpc.go]: You should probably check the error here.  What you should do I'm not sure.  Perhaps simply continue.  Looking and the old code no action was taken after this line, so although the error wasn't discarded, ignoring it was harmless.  But with these changes I guess it's not.

File: grpc.go [hunk 8]
```diff
@@ -56,40 +58,93 @@ type onlineResource struct {
...
+
+func onlineCPUResources(nbCpus uint32) error {
+	resource := onlineResource{
+		sysfsOnlinePath: sysfsCPUOnlinePath,
+		regexpPattern:   cpuRegexpPattern,
+	}
+
+	var count uint32
+	for i := uint32(0); i < onlineCPUMaxTries; i++ {
+		r, err := onlineResources(resource, int32(nbCpus-count))
```
Comment (markdryan) [inline grpc.go]: Do the directory contents of resource.sysfsOnlinePath change between invocations of this function?  If not do you need to read the directory up to 10 times and check the online files 10 times.  I'm suppose I'm thinking of a situation in which in the first invocation you online 4 out of 5 cpus.  If I read the code correctly you'd then re-read the online files associated with those CPUs up to 9 more times.

Comment (devimc) [reply grpc.go]: In systems running low on resources, yes. Read the directory in each iteration is needed

File: grpc.go [hunk 9]
```diff
@@ -56,40 +61,95 @@ type onlineResource struct {
...
+		if err != nil {
+			// resource cold plugged
+			continue
+		}
 
-			if !matched {
-				continue
+		if strings.Trim(string(status), "\n\t ") == "0" {
+			if err := ioutil.WriteFile(onlinePath, []byte("1"), 0600); err != nil {
+				return count, err
```
Comment (markdryan) [inline grpc.go]: If you get one write error you'll give up entirely, i.e., the for loop in onlineCPUResources will terminate.  Is this intentional?

File: grpc.go [hunk 10]
```diff
@@ -752,7 +807,10 @@ func (a *agentGRPC) UpdateRoutes(ctx context.Context, req *pb.UpdateRoutesReques
 }
 
 func (a *agentGRPC) OnlineCPUMem(ctx context.Context, req *pb.OnlineCPUMemRequest) (*gpb.Empty, error) {
-	go onlineCPUMem()
+	if !req.Wait {
```
[the remark this answers is not in the document]
Comment (devimc) [reply grpc.go]: In order to have a fast boot time, the go routine should run inside the VM, otherwise the runtime fails with next error

```
rpc error: code = Unavailable desc = transport is closing.
```

File: grpc.go (hunk 7 above)
Comment (devimc) [reply grpc.go]: fixed, thanks

Comment (markdryan) [reply grpc.go]: I'm not sure it's fixed correctly though.  If you get one write error you'll give up entirely, i.e., the for loop in onlineCPUResources will terminate. Is this intentional?

File: grpc.go (hunk 9 above)
Comment (devimc) [reply grpc.go]: you're right, would be better to log the error and continue

**Comment by devimc** [comment]
@markdryan @sboeuf  PTAL

**Comment by devimc** [comment]
:slightly_frowning_face:

**Comment by sboeuf** [comment]
@bergwolf @laijs PTAL

File: grpc.go [hunk 11]
```diff
@@ -56,40 +61,96 @@ type onlineResource struct {
...
+			if err := ioutil.WriteFile(onlinePath, []byte("1"), 0600); err != nil {
+				agentLog.WithField("online-path", onlinePath).WithError(err).Errorf("Could not online resource")
 				continue
 			}
+			count++
+		}
 
-			onlinePath := filepath.Join(resource.sysfsOnlinePath, file.Name(), "online")
-			ioutil.WriteFile(onlinePath, []byte("1"), 0600)
+		if nbResources > 0 && count == uint32(nbResources) {
```
Comment (bergwolf) [inline grpc.go]: nits: move it to after `count++`. It only makes sense to check when `count` increases.

**Comment by devimc** [comment]
@bergwolf changes applied , thanks

**Comment by devimc** [comment]
ping @kata-containers/agent

File: grpc.go [hunk 12]
```diff
@@ -43,10 +45,13 @@ const (
 
 // CPU and Memory hotplug
 const (
+	cpuRegexpPattern = "cpu[0-9]*"
+	memRegexpPattern = "memory[0-9]*"
```
Comment (jodh-intel) [inline grpc.go]: Nit: shouldn't these be strictly?:

```
cpuRegexpPattern = "cpu[0-9][0-9]*"
memRegexpPattern = "memory[0-9][0-9]*"
```

Comment (jodh-intel) [reply grpc.go]: It's fine as long as files called `cpu` or `memory` are never created in that directory.

File: grpc.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (sboeuf) [reply grpc.go]: Ok makes sense!

File: protocols/grpc/agent.proto [hunk 13]
```diff
@@ -187,6 +187,13 @@ message UpdateRoutesRequest {
 }
 
 message OnlineCPUMemRequest {
+	// Wait specifies if the caller waits for the agent to online all resources.
+	// If true the agent returns until all resources have been connected, else all
```
Comment (sboeuf) [inline protocols/grpc/agent.proto]: s/`until`/`once`/

Comment (sboeuf) [reply protocols/grpc/agent.proto]: s/`else`/`otherwise`/

File: protocols/grpc/agent.proto [hunk 14]
```diff
@@ -187,6 +187,13 @@ message UpdateRoutesRequest {
...
+	// resources are connected asynchronously and the agent returns immediately
```
Comment (sboeuf) [inline protocols/grpc/agent.proto]: s/`immediately`/`immediately.`/

File: protocols/grpc/agent.proto [hunk 15]
```diff
@@ -187,6 +187,13 @@ message UpdateRoutesRequest {
...
+	bool wait = 1;
+
+	// NbCpus Specifies the number of CPUs that were added and the agent has to online
```
Comment (sboeuf) [inline protocols/grpc/agent.proto]: s/`Specifies`/`specifies`/
s/`online`/`online.`/

**Comment by sboeuf** [comment]
@markdryan could you give this a last review before we merge ?

File: grpc.go [hunk 16]
```diff
@@ -56,40 +61,99 @@ type onlineResource struct {
...
-			regexpPattern:   memRegexpPattern,
-		},
+var onlineCPUMemLock sync.Mutex
+
+const onlineCPUMemWaitTime = 100 * time.Millisecond
+
+const onlineCPUMaxTries = 10
+
+// online resources, nbResources specifies the maximum number of resources to online.
+// If nbResources is -1 then there is no limit, all resources are connected
```
Comment (markdryan) [inline grpc.go]: Looking at the code, there's no limit if nbResources==0 either.

**Comment by markdryan** [comment]
@sboeuf Looks good to me.  I think my comments have been addressed.  I made one small comment on a comment.

**Comment by sboeuf** [comment]
@devimc please address both comments from @markdryan and myself, and we're good to merge this :)

**Comment by devimc** [comment]
@markdryan @sboeuf  changes applied, thanks

**Comment by sboeuf** [comment]
Thanks @devimc, let's merge it !
